# Generated by Django 4.2.7 on 2023-12-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreIns', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('idins', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('hora_inscripcion', models.TimeField()),
                ('estado', models.CharField(max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='SG_Ev3y4_app.institucion')),
            ],
        ),
    ]
