# Generated by Django 4.2.7 on 2023-12-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SG_Ev3y4_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='nombreIns',
            new_name='Nombre_Institucion',
        ),
    ]
